In [38]:
import pandas as pd
import json
from urllib.request import urlretrieve

In [39]:
url = "https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json"
path = "data/台北市Youbike2.0jsondata.json" 
urlretrieve(url, path)
with open(path,"r" , encoding = "utf-8-sig") as file:
    data = json.load(file)

In [40]:
df = pd.DataFrame(data)
df.head()

,sno,sna,sarea,mday,ar,sareaen,snaen,aren,act,srcUpdateTime,updateTime,infoTime,infoDate,Quantity,available_rent_bikes,latitude,longitude,available_return_bikes
0,500101001,YouBike2.0_捷運科技大樓站,大安區,2026-10-13 00:59:03,復興南路二段235號前,Daan Dist.,YouBike2.0_MRT Technology Bldg. Sta.,No.235， Sec. 2， Fuxing S. Rd.,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,28,12,25.02605,121.54360,15
1,500101002,YouBike2.0_復興南路二段273號前,大安區,2026-10-13 00:59:03,復興南路二段273號西側,Daan Dist.,YouBike2.0_No.273， Sec. 2， Fuxing S. Rd.,No.273， Sec. 2， Fuxing S. Rd. (West),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,21,8,25.02565,121.54357,12
2,500101003,YouBike2.0_國北教大實小東側門,大安區,2026-10-13 00:59:03,和平東路二段96巷7號,Daan Dist.,YouBike2.0_NTUE Experiment Elementary School (...,No. 7， Ln. 96， Sec. 2， Heping E. Rd,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,28,22,25.02429,121.54124,4
3,500101004,YouBike2.0_和平公園東側,大安區,2026-10-13 00:59:03,和平東路二段118巷33號,Daan Dist.,YouBike2.0_Heping Park (East),No. 33， Ln. 118， Sec. 2， Heping E. Rd,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,11,7,25.02351,121.54282,2
4,500101005,YouBike2.0_辛亥復興路口西北側,大安區,2026-10-13 00:59:03,復興南路二段368號,Daan Dist.,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,No. 368， Sec. 2， Fuxing S. Rd.,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,16,7,25.02153,121.54299,8

In [41]:
df.columns

Index(['sno', 'sna', 'sarea', 'mday', 'ar', 'sareaen', 'snaen', 'aren', 'act',
       'srcUpdateTime', 'updateTime', 'infoTime', 'infoDate', 'Quantity',
       'available_rent_bikes', 'latitude', 'longitude',
       'available_return_bikes'],
      dtype='str')

In [42]:
df["sna"]

0           YouBike2.0_捷運科技大樓站
1       YouBike2.0_復興南路二段273號前
2         YouBike2.0_國北教大實小東側門
3            YouBike2.0_和平公園東側
4         YouBike2.0_辛亥復興路口西北側
                 ...
1814        YouBike2.0_臺大博理館北側
1815        YouBike2.0_臺大博理館東側
1816       YouBike2.0_臺大德田館東北側
1817      YouBike2.0_臺大普通教學館東側
1818      YouBike2.0_臺大次震宇宙館西側
Name: sna, Length: 1819, dtype: str

In [59]:
df = df.rename(columns={"sna": "場站", "sarea": "場站區域", "ar": "地點", "available_rent_bikes": "目前車輛數", "mday": "更新時間"})
df

,sno,場站,場站區域,更新時間,地點,sareaen,snaen,aren,act,srcUpdateTime,updateTime,infoTime,infoDate,Quantity,目前車輛數,latitude,longitude,available_return_bikes
0,500101001,YouBike2.0_捷運科技大樓站,大安區,2026-10-13 00:59:03,復興南路二段235號前,Daan Dist.,YouBike2.0_MRT Technology Bldg. Sta.,No.235， Sec. 2， Fuxing S. Rd.,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,28,12,25.02605,121.54360,15
1,500101002,YouBike2.0_復興南路二段273號前,大安區,2026-10-13 00:59:03,復興南路二段273號西側,Daan Dist.,YouBike2.0_No.273， Sec. 2， Fuxing S. Rd.,No.273， Sec. 2， Fuxing S. Rd. (West),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,21,8,25.02565,121.54357,12
2,500101003,YouBike2.0_國北教大實小東側門,大安區,2026-10-13 00:59:03,和平東路二段96巷7號,Daan Dist.,YouBike2.0_NTUE Experiment Elementary School (...,No. 7， Ln. 96， Sec. 2， Heping E. Rd,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,28,22,25.02429,121.54124,4
3,500101004,YouBike2.0_和平公園東側,大安區,2026-10-13 00:59:03,和平東路二段118巷33號,Daan Dist.,YouBike2.0_Heping Park (East),No. 33， Ln. 118， Sec. 2， Heping E. Rd,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,11,7,25.02351,121.54282,2
4,500101005,YouBike2.0_辛亥復興路口西北側,大安區,2026-10-13 00:59:03,復興南路二段368號,Daan Dist.,YouBike2.0_Xinhai Fuxing Rd. Intersection (Nor...,No. 368， Sec. 2， Fuxing S. Rd.,1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,16,7,25.02153,121.54299,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1814,500119099,YouBike2.0_臺大博理館北側,臺大公館校區,2026-10-13 00:59:03,臺大博理館北側,NTU Dist,YouBike2.0_NTU Barry Lam Hall(North),NTU Barry Lam Hall(North),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,36,1,25.01945,121.54245,34
1815,500119100,YouBike2.0_臺大博理館東側,臺大公館校區,2026-10-13 00:59:03,臺大博理館東側,NTU Dist,YouBike2.0_NTU Barry Lam Hall(East),NTU Barry Lam Hall(North),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,24,0,25.01929,121.54264,24
1816,500119101,YouBike2.0_臺大德田館東北側,臺大公館校區,2026-10-13 00:59:03,臺大德田館東北側,NTU Dist,YouBike2.0_NTU Der Tian Hall (Northeast),NTU Der Tian Hall (Northeast),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,56,0,25.01976,121.54197,56
1817,500119102,YouBike2.0_臺大普通教學館東側,臺大公館校區,2026-10-13 00:59:03,臺大普通教學館東側,NTU Dist,YouBike2.0_NTU Putong Lecture Building (East),NTU Putong Lecture Building (East),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,42,0,25.01861,121.53717,42
1818,500119103,YouBike2.0_臺大次震宇宙館西側,臺大公館校區,2026-10-13 00:59:03,臺大次震宇宙館西側,NTU Dist,YouBike2.0_NTU Cosmology Hall (West),NTU Cosmology Hall (West),1,2026-10-13 00:59:52,2026-10-13 00:59:52,2026-10-13 00:59:03,2026-10-13,34,0,25.02162,121.53700,34

In [62]:
print("更新時間：")
print(df.iloc[0]["更新時間"])
df[["場站", "場站區域", "地點", "目前車輛數", "更新時間"]]

更新時間：
2026-10-13 00:59:03

,場站,場站區域,地點,目前車輛數,更新時間
0,YouBike2.0_捷運科技大樓站,大安區,復興南路二段235號前,12,2026-10-13 00:59:03
1,YouBike2.0_復興南路二段273號前,大安區,復興南路二段273號西側,8,2026-10-13 00:59:03
2,YouBike2.0_國北教大實小東側門,大安區,和平東路二段96巷7號,22,2026-10-13 00:59:03
3,YouBike2.0_和平公園東側,大安區,和平東路二段118巷33號,7,2026-10-13 00:59:03
4,YouBike2.0_辛亥復興路口西北側,大安區,復興南路二段368號,7,2026-10-13 00:59:03
...,...,...,...,...,...
1814,YouBike2.0_臺大博理館北側,臺大公館校區,臺大博理館北側,1,2026-10-13 00:59:03
1815,YouBike2.0_臺大博理館東側,臺大公館校區,臺大博理館東側,0,2026-10-13 00:59:03
1816,YouBike2.0_臺大德田館東北側,臺大公館校區,臺大德田館東北側,0,2026-10-13 00:59:03
1817,YouBike2.0_臺大普通教學館東側,臺大公館校區,臺大普通教學館東側,0,2026-10-13 00:59:03
1818,YouBike2.0_臺大次震宇宙館西側,臺大公館校區,臺大次震宇宙館西側,0,2026-10-13 00:59:03

In [63]:
result = df[["場站", "場站區域", "地點", "目前車輛數", "更新時間"]]
result.to_excel("data/YouBike2.0整理後資料.xlsx", index=False)